import SwiftUI

/// Final Cut for AI production. A real NLE surface — lanes, clips, blade, ripple,
/// slip — where every clip also carries what generated it and what it cost, and
/// "regenerate this shot" is an edit like any other.
struct CuttingRoomView: View {
    @EnvironmentObject private var model: ProductionViewModel
    @State private var pixelsPerSecond: Double = 12
    @State private var regenerationTool: String = ""
    @State private var queuedTask: PlanTask?
    @State private var exportURL: URL?

    /// Never seeds during view evaluation — the assembly is built in onAppear.
    private var timeline: Timeline { model.timeline ?? Timeline() }

    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                statsBar
                TimelineStripView(timeline: timeline,
                                  pixelsPerSecond: pixelsPerSecond,
                                  selectedClipID: $model.selectedClipID)
                    .frame(height: 190)
                Divider()
                inspector
            }
            .navigationTitle("Cutting room")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button("Rebuild assembly from the plan") {
                            model.seedTimeline(force: true)
                        }
                        Divider()
                        Button("Export EDL") { exportURL = model.export(.edl) }
                        Button("Export FCPXML") { exportURL = model.export(.fcpxml) }
                        Button("Export OTIO") { exportURL = model.export(.otio) }
                    } label: {
                        Image(systemName: "ellipsis.circle")
                    }
                }
                if let exportURL {
                    ToolbarItem(placement: .topBarLeading) {
                        ShareLink(item: exportURL) { Image(systemName: "square.and.arrow.up") }
                    }
                }
            }
            .onAppear {
                model.seedTimeline()
                if regenerationTool.isEmpty { regenerationTool = model.plan.toolsUsed.first ?? "" }
            }
        }
    }

    private var statsBar: some View {
        VStack(spacing: 8) {
            StatGrid(stats: [
                ("Duration", Clock.duration(timeline.duration)),
                ("Clips", "\(timeline.clipCount)"),
                ("Cost of cut", Money.compact(timeline.costOfCut)),
                ("Unused takes", Money.compact(timeline.costOfUnusedTakes)),
            ])
            HStack {
                Image(systemName: "minus.magnifyingglass")
                Slider(value: $pixelsPerSecond, in: 2...60)
                Image(systemName: "plus.magnifyingglass")
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
    }

    @ViewBuilder
    private var inspector: some View {
        if let clipID = model.selectedClipID, let clip = timeline.clip(clipID) {
            List {
                Section(clip.name) {
                    KeyValueRow(key: "Track", value: timeline.trackID(of: clip.id) ?? "—")
                    KeyValueRow(key: "In / out", value: "\(Clock.timecode(clip.start, fps: timeline.fps)) → \(Clock.timecode(clip.end, fps: timeline.fps))")
                    KeyValueRow(key: "Source", value: "\(String(format: "%.2f", clip.sourceIn)) – \(String(format: "%.2f", clip.sourceOut))")
                    KeyValueRow(key: "Generated by", value: clip.provenance.toolID ?? "—")
                    KeyValueRow(key: "Cost of this take", value: Money.string(clip.provenance.cost))
                    KeyValueRow(key: "Takes", value: "\(clip.takes.count)")
                    if let prompt = clip.provenance.prompt {
                        Text(prompt).font(.caption2).foregroundStyle(.secondary)
                    }
                }

                Section("Edit") {
                    Button("Blade at midpoint") {
                        model.edit { try $0.blade(clip.id, at: clip.start + clip.duration / 2) }
                    }
                    Button("Trim 0.5s off the tail (ripple)") {
                        model.edit { try $0.trim(clip.id, tail: min(0.5, clip.duration / 2), ripple: true) }
                    }
                    Button("Slip source +0.25s") {
                        model.edit { try $0.slip(clip.id, by: 0.25) }
                    }
                    Button("Dissolve in") {
                        model.edit { try $0.setTransition(clip.id, transition: Transition()) }
                    }
                    Button("Ripple delete", role: .destructive) {
                        model.edit { _ = try $0.rippleDelete(clip.id) }
                        model.selectedClipID = nil
                    }
                }

                Section("Takes") {
                    ForEach(clip.takes) { take in
                        Button {
                            model.edit { try $0.selectTake(take.id, on: clip.id) }
                        } label: {
                            HStack {
                                Image(systemName: take.id == clip.provenance.takeID ? "largecircle.fill.circle" : "circle")
                                Text(take.toolID)
                                Spacer()
                                Text(Money.string(take.cost)).monospacedDigit().foregroundStyle(.secondary)
                            }
                        }
                    }
                }

                Section {
                    Picker("Generator", selection: $regenerationTool) {
                        ForEach(model.registry.tools.filter { $0.capabilities.contains(Capability.videoTextToVideo) }) { tool in
                            Text(tool.name).tag(tool.id)
                        }
                    }
                    Button("Send back to the orchestra") {
                        queuedTask = model.regenerateSelectedClip(using: regenerationTool)
                    }
                    if let queuedTask {
                        Text("Queued \(queuedTask.label) on \(queuedTask.toolID) — \(Money.string(queuedTask.cost)) for \(String(format: "%.1f", queuedTask.units))s")
                            .font(.caption).foregroundStyle(Palette.accent)
                    }
                } header: {
                    Text("Regenerate")
                } footer: {
                    Text("Same slot, same length, new take. The take stack keeps the old one, so the cut's cost — and what you spent on takes nobody sees — stays honest.")
                }
            }
        } else {
            ContentUnavailableView("Select a clip",
                                   systemImage: "film",
                                   description: Text("Tap a clip to trim it, swap takes, or send it back to the orchestra."))
        }
    }
}

/// The lanes. Drawn with Canvas rather than a view per clip — a feature is a
/// thousand-plus clips, and a thousand SwiftUI views would crawl.
struct TimelineStripView: View {
    var timeline: Timeline
    var pixelsPerSecond: Double
    @Binding var selectedClipID: String?

    var body: some View {
        ScrollView([.horizontal, .vertical]) {
            VStack(alignment: .leading, spacing: 6) {
                ForEach(timeline.tracks) { track in
                    HStack(spacing: 6) {
                        Text(track.id)
                            .font(.caption2.monospaced())
                            .foregroundStyle(.secondary)
                            .frame(width: 26, alignment: .leading)
                        laneCanvas(for: track)
                    }
                }
            }
            .padding(10)
        }
        .background(Color(.systemBackground))
    }

    private func laneCanvas(for track: Track) -> some View {
        let width = max(240, timeline.duration * pixelsPerSecond)
        return Canvas { context, size in
            for clip in track.clips {
                let rect = CGRect(x: clip.start * pixelsPerSecond,
                                  y: 0,
                                  width: max(1.5, clip.duration * pixelsPerSecond - 1),
                                  height: size.height)
                let isSelected = clip.id == selectedClipID
                let fill = track.kind == .video
                    ? Color(red: 0.16, green: 0.22, blue: 0.28)
                    : Color(red: 0.11, green: 0.24, blue: 0.18)
                context.fill(Path(roundedRect: rect, cornerRadius: 3), with: .color(fill))
                if isSelected {
                    context.stroke(Path(roundedRect: rect, cornerRadius: 3), with: .color(Palette.accent), lineWidth: 2)
                }
                if rect.width > 26 {
                    context.draw(Text(clip.name).font(.system(size: 8, design: .monospaced)).foregroundColor(.white.opacity(0.8)),
                                 at: CGPoint(x: rect.minX + 4, y: rect.midY), anchor: .leading)
                }
            }
        }
        .frame(width: width, height: 44)
        .contentShape(Rectangle())
        .gesture(
            DragGesture(minimumDistance: 0).onEnded { value in
                let seconds = value.location.x / pixelsPerSecond
                if let hit = track.clips.first(where: { seconds >= $0.start && seconds <= $0.end }) {
                    selectedClipID = hit.id
                }
            }
        )
    }
}
