import SwiftUI

/// A slider that only writes an undo step when the finger lifts. Dragging one
/// would otherwise bury the undo stack under a hundred intermediate values.
struct CommitSlider: View {
    var label: String
    var range: ClosedRange<Double>
    var step: Double
    var format: (Double) -> String
    var initial: Double
    var commit: (Double) -> Void

    @State private var value: Double = 0
    @State private var isEditing = false

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack {
                Text(label).font(.caption)
                Spacer()
                Text(format(value)).font(.caption.monospacedDigit()).foregroundStyle(.secondary)
            }
            Slider(value: $value, in: range, step: step) { editing in
                isEditing = editing
                if !editing { commit(value) }
            }
        }
        .onAppear { value = initial }
        .onChange(of: initial) { _, new in
            if !isEditing { value = new }
        }
    }
}

// MARK: - Info

struct InfoInspector: View {
    @ObservedObject var doc: CutDocument
    var placed: PlacedItem
    @State private var markerName: String = ""

    private var item: TimelineItem { placed.item }

    var body: some View {
        List {
            Section(item.name) {
                KeyValueRow(key: "Lane", value: placed.lane == 0 ? "Primary storyline" : "Lane \(placed.lane)")
                KeyValueRow(key: "Start", value: placed.start.timecode(at: doc.rate))
                KeyValueRow(key: "End", value: placed.end.timecode(at: doc.rate))
                KeyValueRow(key: "Duration", value: item.duration.timecode(at: doc.rate))
                KeyValueRow(key: "Source in", value: item.sourceIn.timecode(at: doc.rate))
                KeyValueRow(key: "Role", value: item.role.label)
                KeyValueRow(key: "Generated by", value: item.provenance.toolID ?? "—")
                KeyValueRow(key: "Cost of this take", value: Money.string(item.cost))
                if item.costOfDiscardedTakes > 0 {
                    KeyValueRow(key: "Spent on unused takes", value: Money.string(item.costOfDiscardedTakes))
                }
            }

            Section("Trim") {
                TrimPad(doc: doc)
            }

            Section("Roles") {
                Picker("Role", selection: Binding(
                    get: { item.role },
                    set: { doc.setRoleOnSelection($0) }
                )) {
                    ForEach(doc.timeline.roles) { role in
                        Text(role.label).tag(role)
                    }
                }
                .pickerStyle(.menu)
            }

            Section("Flags") {
                Button {
                    doc.toggleEnabledOnSelection()
                } label: {
                    Label(item.isEnabled ? "Disable clip" : "Enable clip",
                          systemImage: item.isEnabled ? "eye.slash" : "eye")
                }
                Button {
                    doc.toggleLockOnSelection()
                } label: {
                    Label(item.isLocked ? "Unlock clip" : "Lock clip",
                          systemImage: item.isLocked ? "lock.open" : "lock")
                }
                HStack {
                    Button {
                        doc.rateSelection(item.rating == .favorite ? nil : .favorite)
                    } label: {
                        Label("Favourite", systemImage: item.rating == .favorite ? "star.fill" : "star")
                    }
                    .tint(Palette.good)
                    Spacer()
                    Button {
                        doc.rateSelection(item.rating == .rejected ? nil : .rejected)
                    } label: {
                        Label("Reject", systemImage: item.rating == .rejected ? "xmark.circle.fill" : "xmark.circle")
                    }
                    .tint(Palette.bad)
                }
                .buttonStyle(.borderless)
            }

            Section("Markers") {
                HStack {
                    TextField("Marker name", text: $markerName)
                    Button("Add") {
                        doc.addMarkerAtPlayhead(name: markerName.isEmpty ? "Marker" : markerName)
                        markerName = ""
                        Haptics.tap()
                    }
                    .buttonStyle(.borderless)
                }
                ForEach(item.markers) { marker in
                    Label {
                        VStack(alignment: .leading, spacing: 1) {
                            Text(marker.name).font(.caption)
                            Text((placed.start + marker.at).timecode(at: doc.rate))
                                .font(.caption2.monospaced())
                                .foregroundStyle(.secondary)
                        }
                    } icon: {
                        Image(systemName: marker.kind.symbol).foregroundStyle(Palette.accent)
                    }
                }
            }

            Section("Structure") {
                Button {
                    doc.makeCompoundFromSelection(named: "Compound Clip")
                } label: {
                    Label("New compound clip from selection", systemImage: "square.stack.3d.down.right")
                }
                .disabled(doc.selection.count < 2)

                if item.content.isCompound {
                    Button {
                        doc.breakApartSelection()
                    } label: {
                        Label("Break apart", systemImage: "square.split.2x1")
                    }
                }
            }
        }
    }
}

/// The four trims Final Cut gives you, each nudging by a frame or a second.
/// Ripple changes the sequence length, roll moves the cut, slip changes what
/// plays without moving anything, slide moves the clip and lets its neighbours
/// absorb it.
struct TrimPad: View {
    @ObservedObject var doc: CutDocument
    @State private var stepFrames: Int64 = 1

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Picker("Step", selection: $stepFrames) {
                Text("1 frame").tag(Int64(1))
                Text("5 frames").tag(Int64(5))
                Text("1 second").tag(Int64(doc.rate.nominalRate))
            }
            .pickerStyle(.segmented)

            trimRow("Ripple head", symbol: "arrow.left.to.line") {
                doc.trimSelection(edge: .head, frames: -stepFrames)
            } forward: {
                doc.trimSelection(edge: .head, frames: stepFrames)
            }

            trimRow("Ripple tail", symbol: "arrow.right.to.line") {
                doc.trimSelection(edge: .tail, frames: stepFrames)
            } forward: {
                doc.trimSelection(edge: .tail, frames: -stepFrames)
            }

            trimRow("Roll edit", symbol: "arrow.left.and.right.righttriangle.left.righttriangle.right") {
                doc.rollSelection(frames: -stepFrames)
            } forward: {
                doc.rollSelection(frames: stepFrames)
            }

            trimRow("Slip source", symbol: "arrow.left.arrow.right.square") {
                doc.slipSelection(frames: -stepFrames)
            } forward: {
                doc.slipSelection(frames: stepFrames)
            }

            trimRow("Slide clip", symbol: "arrow.left.and.right") {
                doc.slideSelection(frames: -stepFrames)
            } forward: {
                doc.slideSelection(frames: stepFrames)
            }
        }
        .padding(.vertical, 2)
    }

    private func trimRow(_ label: String,
                         symbol: String,
                         back: @escaping () -> Void,
                         forward: @escaping () -> Void) -> some View {
        HStack {
            Label(label, systemImage: symbol).font(.caption)
            Spacer()
            Button { back(); Haptics.tap() } label: { Image(systemName: "minus.circle") }
                .accessibilityLabel("\(label) backward")
            Button { forward(); Haptics.tap() } label: { Image(systemName: "plus.circle") }
                .accessibilityLabel("\(label) forward")
        }
        .buttonStyle(.borderless)
    }
}

// MARK: - Video

struct VideoInspector: View {
    @ObservedObject var doc: CutDocument
    var placed: PlacedItem

    private var item: TimelineItem { placed.item }
    private var transform: Transform { item.transform }

    var body: some View {
        List {
            Section("Transform") {
                CommitSlider(label: "Position X", range: -960...960, step: 1,
                             format: { String(format: "%.0f", $0) },
                             initial: transform.positionX.constant) { value in
                    update { $0.transform.positionX.constant = value }
                }
                CommitSlider(label: "Position Y", range: -540...540, step: 1,
                             format: { String(format: "%.0f", $0) },
                             initial: transform.positionY.constant) { value in
                    update { $0.transform.positionY.constant = value }
                }
                CommitSlider(label: "Scale", range: 10...400, step: 1,
                             format: { String(format: "%.0f%%", $0) },
                             initial: transform.scaleX.constant) { value in
                    update {
                        $0.transform.scaleX.constant = value
                        $0.transform.scaleY.constant = value
                    }
                }
                CommitSlider(label: "Rotation", range: -180...180, step: 1,
                             format: { String(format: "%.0f°", $0) },
                             initial: transform.rotation.constant) { value in
                    update { $0.transform.rotation.constant = value }
                }
                CommitSlider(label: "Opacity", range: 0...100, step: 1,
                             format: { String(format: "%.0f%%", $0) },
                             initial: transform.opacity.constant) { value in
                    update { $0.transform.opacity.constant = value }
                }
            }

            Section {
                Button {
                    keyframeOpacityAtPlayhead()
                } label: {
                    Label("Keyframe opacity at playhead", systemImage: "diamond")
                }
                if transform.opacity.isAnimated {
                    ForEach(transform.opacity.keyframes) { keyframe in
                        KeyValueRow(key: (placed.start + keyframe.time).timecode(at: doc.rate),
                                    value: String(format: "%.0f%%", keyframe.value))
                    }
                }
                Button(role: .destructive) {
                    update { $0.transform = Transform() }
                } label: {
                    Label("Reset transform", systemImage: "arrow.counterclockwise")
                }
            } header: {
                Text("Keyframes")
            } footer: {
                Text("Keyframe times are measured from the clip's own head, so trimming the front does not slide the animation off it.")
            }
        }
    }

    private func update(_ change: @escaping (inout TimelineItem) -> Void) {
        let id = item.id
        doc.perform("Adjust Video") { timeline in
            try timeline.update(id: id) { change(&$0) }
        }
    }

    private func keyframeOpacityAtPlayhead() {
        let relative = doc.playhead - placed.start
        guard !relative.isNegative, relative < item.duration else { return }
        let current = transform.opacity.value(at: relative)
        update { $0.transform.opacity.setKeyframe(at: relative, value: current) }
        Haptics.tap()
    }
}

// MARK: - Audio

struct AudioInspector: View {
    @ObservedObject var doc: CutDocument
    var placed: PlacedItem

    private var item: TimelineItem { placed.item }

    var body: some View {
        List {
            Section("Level") {
                CommitSlider(label: "Volume", range: -60...12, step: 0.5,
                             format: { String(format: "%+.1f dB", $0) },
                             initial: item.audio.volumeDB.constant) { value in
                    update { $0.audio.volumeDB.constant = value }
                }
                CommitSlider(label: "Pan", range: -100...100, step: 1,
                             format: { String(format: "%.0f", $0) },
                             initial: item.audio.pan.constant) { value in
                    update { $0.audio.pan.constant = value }
                }
                Toggle("Mute", isOn: Binding(
                    get: { item.audio.isMuted },
                    set: { muted in update { $0.audio.isMuted = muted } }
                ))
            }

            Section {
                CommitSlider(label: "Fade in", range: 0...5, step: 0.1,
                             format: { String(format: "%.1f s", $0) },
                             initial: item.audio.fadeIn.duration.seconds) { value in
                    doc.setFadeOnSelection(edge: .head, seconds: value, shape: .easeIn)
                }
                CommitSlider(label: "Fade out", range: 0...5, step: 0.1,
                             format: { String(format: "%.1f s", $0) },
                             initial: item.audio.fadeOut.duration.seconds) { value in
                    doc.setFadeOnSelection(edge: .tail, seconds: value, shape: .easeOut)
                }
            } header: {
                Text("Fades")
            } footer: {
                Text("Gain at the playhead: \(String(format: "%.2f×", gainAtPlayhead))")
            }

            Section("Split edits") {
                Button {
                    doc.detachAudioFromSelection()
                } label: {
                    Label("Detach audio to its own lane", systemImage: "waveform.badge.minus")
                }
                Button {
                    doc.detachAudioFromSelection(leadFrames: doc.rate.nominalRate)
                } label: {
                    Label("Detach as J-cut (audio leads 1s)", systemImage: "arrow.turn.left.up")
                }
            }

            Section("Transitions") {
                Button {
                    doc.addTransitionToSelection(edge: .head)
                } label: {
                    Label("Cross dissolve at head", systemImage: "square.on.square.dashed")
                }
                if item.transitionIn != nil {
                    Button(role: .destructive) {
                        let id = item.id
                        doc.perform("Remove Transition") { timeline in
                            try timeline.removeTransition(from: id, edge: .head)
                        }
                    } label: {
                        Label("Remove transition", systemImage: "xmark")
                    }
                }
            }
        }
    }

    private var gainAtPlayhead: Double {
        let relative = doc.playhead - placed.start
        guard !relative.isNegative, relative < item.duration else { return 0 }
        return item.audio.gain(at: relative, clipDuration: item.duration)
    }

    private func update(_ change: @escaping (inout TimelineItem) -> Void) {
        let id = item.id
        doc.perform("Adjust Audio") { timeline in
            try timeline.update(id: id) { change(&$0) }
        }
    }
}

// MARK: - Retime

struct RetimeInspector: View {
    @ObservedObject var doc: CutDocument
    var placed: PlacedItem
    @State private var rampFrom: Double = 100
    @State private var rampTo: Double = 25

    private var item: TimelineItem { placed.item }

    var body: some View {
        List {
            Section {
                KeyValueRow(key: "Current speed", value: item.speedLabel ?? "100%")
                KeyValueRow(key: "Timeline length", value: item.duration.timecode(at: doc.rate))
                KeyValueRow(key: "Source consumed", value: item.sourceUsed.timecode(at: doc.rate))
            } header: {
                Text("Speed")
            } footer: {
                Text("Changing speed changes how long the clip runs, and the storyline is magnetic — everything after it moves to suit.")
            }

            Section("Presets") {
                ForEach([25.0, 50.0, 100.0, 200.0, 400.0], id: \.self) { percent in
                    Button {
                        doc.setSpeedOnSelection(percent: percent)
                        Haptics.tap()
                    } label: {
                        HStack {
                            Text(String(format: "%.0f%%", percent))
                            Spacer()
                            if percent < 100 { Text("slow").font(.caption).foregroundStyle(.secondary) }
                            if percent > 100 { Text("fast").font(.caption).foregroundStyle(.secondary) }
                        }
                    }
                }
            }

            Section("Speed ramp") {
                CommitSlider(label: "From", range: 10...400, step: 5,
                             format: { String(format: "%.0f%%", $0) },
                             initial: rampFrom) { rampFrom = $0 }
                CommitSlider(label: "To", range: 10...400, step: 5,
                             format: { String(format: "%.0f%%", $0) },
                             initial: rampTo) { rampTo = $0 }
                Button {
                    doc.setSpeedRampOnSelection(from: rampFrom, to: rampTo)
                    Haptics.success()
                } label: {
                    Label("Apply ramp", systemImage: "gauge.with.needle")
                }
            }

            if item.retime != nil {
                Section {
                    Button(role: .destructive) {
                        doc.clearSpeedOnSelection()
                    } label: {
                        Label("Reset to 100%", systemImage: "arrow.counterclockwise")
                    }
                }
            }
        }
    }
}

// MARK: - Takes

struct TakesInspector: View {
    @ObservedObject var doc: CutDocument
    var placed: PlacedItem
    var model: ProductionViewModel
    @State private var regenerationTool: String = ""

    private var item: TimelineItem { placed.item }

    var body: some View {
        List {
            Section {
                if let audition = item.audition, !audition.alternatives.isEmpty {
                    ForEach(audition.alternatives) { take in
                        Button {
                            doc.selectTake(take.id, on: item.id)
                            Haptics.tap()
                        } label: {
                            HStack {
                                Image(systemName: take.id == audition.selected?.id
                                      ? "largecircle.fill.circle" : "circle")
                                VStack(alignment: .leading, spacing: 1) {
                                    Text(take.toolID).font(.subheadline)
                                    if let prompt = take.prompt {
                                        Text(prompt).font(.caption2).foregroundStyle(.secondary).lineLimit(1)
                                    }
                                }
                                Spacer()
                                Text(Money.string(take.cost))
                                    .font(.caption.monospacedDigit())
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                } else {
                    Text("No takes on this clip yet.").font(.caption).foregroundStyle(.secondary)
                }
            } header: {
                Text("Audition")
            } footer: {
                Text("Final Cut calls this an audition: alternatives parked on one clip with a single pick. Here the pick also moves money — the cut's cost follows whichever take is live.")
            }

            Section {
                Picker("Generator", selection: $regenerationTool) {
                    ForEach(model.registry.tools.filter {
                        $0.capabilities.contains(Capability.videoTextToVideo)
                    }) { tool in
                        Text(tool.name).tag(tool.id)
                    }
                }
                Button {
                    regenerate()
                } label: {
                    Label("Send back to the orchestra", systemImage: "arrow.triangle.2.circlepath")
                }
                .disabled(regenerationTool.isEmpty)
            } header: {
                Text("Regenerate")
            } footer: {
                Text("Same slot, same length, new take. The old one stays in the audition, so what you spent on takes nobody sees stays visible.")
            }
        }
        .onAppear {
            if regenerationTool.isEmpty {
                regenerationTool = model.plan.toolsUsed.first ?? ""
            }
        }
    }

    private func regenerate() {
        let tool = model.registry.tool(id: regenerationTool)
        let seconds = item.duration.seconds
        let cost = tool?.estimatedCost(units: seconds) ?? 0
        let take = Take(toolID: regenerationTool,
                        cost: cost,
                        prompt: item.provenance.prompt ?? item.name)
        doc.addTake(take, to: item.id)
        Haptics.success()
    }
}
