import Foundation

/// Get the cut out of here. Provenance rides along as comments and metadata, so
/// the next tool downstream still knows what generated each frame and what it cost.
enum Exporters {

    // MARK: - CMX3600 EDL

    static func edl(_ timeline: Timeline, title: String? = nil) -> String {
        var lines = ["TITLE: \((title ?? timeline.name).uppercased())", "FCM: NON-DROP FRAME", ""]
        var event = 0
        for track in timeline.tracks {
            let channel = track.kind == .video ? "V" : "A"
            for clip in track.clips.sorted(by: { $0.start < $1.start }) {
                event += 1
                let transition = clip.transitionIn.map { "D    \(Int(($0.duration * timeline.fps).rounded()))" } ?? "C        "
                let sourceIn = Clock.timecode(clip.sourceIn, fps: timeline.fps)
                let sourceOut = Clock.timecode(clip.sourceOut, fps: timeline.fps)
                let recordIn = Clock.timecode(clip.start, fps: timeline.fps)
                let recordOut = Clock.timecode(clip.end, fps: timeline.fps)
                lines.append(String(format: "%03d  AX       %@     %@ %@ %@ %@ %@", event, channel, transition, sourceIn, sourceOut, recordIn, recordOut))
                lines.append("* FROM CLIP NAME: \(clip.name)")
                if let toolID = clip.provenance.toolID {
                    lines.append(String(format: "* GENERATED BY: %@ COST $%.4f", toolID, clip.provenance.cost))
                }
                lines.append("")
            }
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - FCPXML

    static func fcpxml(_ timeline: Timeline) -> String {
        let fps = timeline.fps
        func time(_ seconds: Double) -> String {
            let scale = Int((fps * 100).rounded())
            return "\(Int((seconds * Double(scale)).rounded()))/\(scale)s"
        }

        let videoClips = timeline.tracks.filter { $0.kind == .video }.flatMap(\.clips).sorted { $0.start < $1.start }
        let audioClips = timeline.tracks.filter { $0.kind == .audio }.flatMap(\.clips).sorted { $0.start < $1.start }
        let everything = videoClips + audioClips

        var assetIDs: [String: String] = [:]
        var assets: [String] = []
        for (index, clip) in everything.enumerated() {
            let id = "a\(index + 1)"
            assetIDs[clip.id] = id
            assets.append("      <asset id=\"\(id)\" name=\"\(escape(clip.name))\" duration=\"\(time(max(clip.sourceOut, clip.duration)))\" hasVideo=\"1\" hasAudio=\"1\"/>")
        }

        let spine = videoClips.map { clip -> String in
            let note = "\(clip.provenance.toolID ?? "unknown") · \(Money.string(clip.provenance.cost)) · \(clip.provenance.prompt ?? "")"
            return """
                      <asset-clip ref="\(assetIDs[clip.id] ?? "a1")" name="\(escape(clip.name))" offset="\(time(clip.start))" start="\(time(clip.sourceIn))" duration="\(time(clip.duration))">
                        <note>\(escape(note))</note>
                      </asset-clip>
            """
        }.joined(separator: "\n")

        let audioLanes = audioClips.enumerated().map { index, clip -> String in
            """
                      <asset-clip ref="\(assetIDs[clip.id] ?? "a1")" name="\(escape(clip.name))" lane="\(index + 1)" offset="\(time(clip.start))" start="\(time(clip.sourceIn))" duration="\(time(clip.duration))"/>
            """
        }.joined(separator: "\n")

        let markers = timeline.markers.map { marker in
            "          <marker start=\"\(time(marker.at))\" value=\"\(escape(marker.name))\"/>"
        }.joined(separator: "\n")

        return """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE fcpxml>
        <fcpxml version="1.10">
          <resources>
            <format id="r1" name="FFVideoFormat" frameDuration="1/\(Int(fps))s" width="\(timeline.resolution.width)" height="\(timeline.resolution.height)"/>
        \(assets.joined(separator: "\n"))
          </resources>
          <library name="Cinema Composer Pro">
            <event name="\(escape(timeline.name))">
              <project name="\(escape(timeline.name))">
                <sequence format="r1" duration="\(time(timeline.duration))">
                  <spine>
        \(spine)
        \(audioLanes)
        \(markers)
                  </spine>
                </sequence>
              </project>
            </event>
          </library>
        </fcpxml>
        """
    }

    // MARK: - OpenTimelineIO

    static func otio(_ timeline: Timeline) throws -> Data {
        func rationalTime(_ seconds: Double) -> [String: Any] {
            ["OTIO_SCHEMA": "RationalTime.1", "rate": timeline.fps, "value": (seconds * timeline.fps * 1000).rounded() / 1000]
        }

        let trackPayloads: [[String: Any]] = timeline.tracks.map { track in
            [
                "OTIO_SCHEMA": "Track.1",
                "name": track.id,
                "kind": track.kind == .video ? "Video" : "Audio",
                "children": track.clips.sorted { $0.start < $1.start }.map { clip -> [String: Any] in
                    [
                        "OTIO_SCHEMA": "Clip.1",
                        "name": clip.name,
                        "source_range": [
                            "OTIO_SCHEMA": "TimeRange.1",
                            "start_time": rationalTime(clip.sourceIn),
                            "duration": rationalTime(clip.duration),
                        ],
                        "metadata": [
                            "ccp": [
                                "shotID": clip.shotID ?? "",
                                "timelineStart": clip.start,
                                "toolID": clip.provenance.toolID ?? "",
                                "cost": clip.provenance.cost,
                                "takes": clip.takes.count,
                            ],
                        ],
                    ]
                },
            ]
        }

        let payload: [String: Any] = [
            "OTIO_SCHEMA": "Timeline.1",
            "name": timeline.name,
            "global_start_time": rationalTime(0),
            "metadata": ["generator": "Cinema Composer Pro", "costOfCut": timeline.costOfCut],
            "tracks": ["OTIO_SCHEMA": "Stack.1", "name": "tracks", "children": trackPayloads],
            "markers": timeline.markers.map { marker -> [String: Any] in
                [
                    "OTIO_SCHEMA": "Marker.1",
                    "name": marker.name,
                    "marked_range": ["OTIO_SCHEMA": "TimeRange.1", "start_time": rationalTime(marker.at), "duration": rationalTime(0)],
                ]
            },
        ]
        return try JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted, .sortedKeys])
    }

    // MARK: - Budget CSV

    /// What a producer actually emails to a financier.
    static func csv(_ budget: Budget) -> String {
        func cell(_ value: String) -> String {
            value.contains(where: { ",\"\n".contains($0) }) ? "\"\(value.replacingOccurrences(of: "\"", with: "\"\""))\"" : value
        }
        func row(_ values: [String]) -> String { values.map(cell).joined(separator: ",") }

        var rows: [String] = [
            row(["Cinema Composer Pro budget", budget.project, "\(Int(budget.runtimeMinutes)) min",
                 budget.spec.tier.label, budget.strategy.label]),
            "",
            row(["Department", "Line item", "Tool", "Units", "Unit", "Rate", "Subtotal USD"]),
        ]
        for item in budget.lineItems {
            rows.append(row([item.department.label, item.label, item.toolName,
                             String(format: "%.2f", item.units), item.unitLabel,
                             String(format: "%.4f", item.unitRate), String(format: "%.2f", item.subtotal)]))
        }
        rows.append("")
        rows.append(row(["", "", "", "", "", "Subtotal", String(format: "%.2f", budget.subtotal)]))
        rows.append(row(["", "", "", "", "", "Contingency \(Int(budget.contingencyPercent))%", String(format: "%.2f", budget.contingency)]))
        rows.append(row(["", "", "", "", "", "TOTAL", String(format: "%.2f", budget.total)]))
        rows.append(row(["", "", "", "", "", "Per runtime minute", String(format: "%.2f", budget.unitEconomics.perRuntimeMinute)]))
        rows.append(row(["", "", "", "", "", "Per shot", String(format: "%.2f", budget.unitEconomics.perShot)]))
        if let efficiency = budget.efficiency {
            rows.append(row(["", "", "", "", "", "Naive baseline", String(format: "%.2f", efficiency.baselineTotal)]))
            rows.append(row(["", "", "", "", "", "Saved by optimization", String(format: "%.2f", efficiency.saved)]))
        }
        return rows.joined(separator: "\n")
    }

    // MARK: - Producer's top sheet

    /// The one page that goes in front of a financier: what it costs, where it
    /// goes, what it assumes, and what would change it.
    static func topSheet(budget: Budget, plan: ProductionPlan, breakdown: Breakdown) -> String {
        var lines: [String] = []
        let spec = budget.spec

        lines.append("# \(budget.project)")
        lines.append("")
        lines.append("**\(Int(spec.runtimeMinutes)) minutes · \(spec.genre.label) · \(spec.tier.label) · \(spec.tier.resolutionLabel)**")
        lines.append("")
        lines.append("_\(spec.style)_")
        lines.append("")

        if !budget.isComplete {
            lines.append("> **This budget is incomplete.** " + budget.gaps.map { "\($0.department.label): \($0.reason)" }.joined(separator: " "))
            lines.append("")
        }

        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| **Total** | **\(Money.string(budget.total))** |")
        lines.append("| Per runtime minute | \(Money.string(budget.unitEconomics.perRuntimeMinute)) |")
        lines.append("| Per shot | \(Money.string(budget.unitEconomics.perShot)) (\(budget.shotCount) shots, \(budget.sceneCount) scenes) |")
        lines.append("| AI vs human | \(Int(budget.unitEconomics.aiSharePercent))% tools, \(Int(budget.unitEconomics.humanSharePercent))% people |")
        lines.append("| Schedule | \(Clock.duration(budget.schedule.wallClockSeconds)) wall clock (\(String(format: "%.1f", budget.schedule.speedup))× parallel) |")
        if let efficiency = budget.efficiency {
            lines.append("| Optimization | \(Money.string(efficiency.saved)) below the naive plan (\(String(format: "%.0f", efficiency.savedPercent))%) |")
        }
        lines.append("")

        lines.append("## Where the money goes")
        lines.append("")
        lines.append("| Department | Spend | Share |")
        lines.append("|---|---:|---:|")
        for department in budget.departments {
            lines.append("| \(department.department.label) | \(Money.string(department.subtotal)) | \(String(format: "%.0f%%", department.sharePercent)) |")
        }
        lines.append("| **Subtotal** | **\(Money.string(budget.subtotal))** | |")
        lines.append("| Contingency \(Int(budget.contingencyPercent))% | \(Money.string(budget.contingency)) | |")
        lines.append("| **Total** | **\(Money.string(budget.total))** | |")
        lines.append("")

        if let efficiency = budget.efficiency {
            lines.append("## What the optimizer is doing")
            lines.append("")
            lines.append("Baseline — best tool for every job, no passes: **\(Money.string(efficiency.baselineTotal))**")
            lines.append("")
            for saving in efficiency.passSavings where saving.applied {
                let amount = saving.saved > 0 ? Money.string(saving.saved) : (saving.note ?? "—")
                lines.append("- **\(saving.pass.label)** — \(saving.pass.detail) _(\(amount))_")
            }
            lines.append("")
        }

        let expensive = ShotEconomics.mostExpensive(breakdown: breakdown, plan: plan, limit: 10)
        if !expensive.isEmpty {
            lines.append("## The ten shots to argue about")
            lines.append("")
            lines.append("| Shot | Scene | Length | Generator | Cost |")
            lines.append("|---|---:|---:|---|---:|")
            for row in expensive {
                lines.append("| \(row.shot.id) | \(row.shot.scene) | \(String(format: "%.1fs", row.shot.seconds)) | \(row.toolID) | \(Money.string(row.cost)) |")
            }
            lines.append("")
        }

        lines.append("## Assumptions")
        lines.append("")
        for assumption in budget.assumptions { lines.append("- \(assumption)") }
        lines.append("")
        lines.append("## Tools on this plan")
        lines.append("")
        lines.append(budget.toolsUsed.joined(separator: ", "))
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("Prepared by Cinema Composer Pro · \(budget.generatedAt.formatted(date: .abbreviated, time: .shortened)) · rates are editable defaults, not vendor quotes.")
        return lines.joined(separator: "\n")
    }

    private static func escape(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
